services:
  astraeus-api-node:
    build:
      context: .
      dockerfile: ./docker/api.Dockerfile
    networks:
      - suave-net
    env_file:
      - .env
    ports:
      - 8080:8080
    command: ["make", "run-go"]
networks:
    suave-net:
